#version 450 core
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D depthTexture;
layout(set = 0, binding = 1, r32f) uniform writeonly image2D hiz;

void main() {
	const ivec2 p = ivec2(gl_GlobalInvocationID.xy);
	const ivec2 size = imageSize(hiz);
	if (p.x >= size.x || p.y >= size.y) {
		return;
	}
	const float depth = texelFetch(depthTexture, p, 0).r;
	imageStore(hiz, p, vec4(depth, 0, 0, 0));
}
